### ISSUE TITLE
JOSS review, re: software paper

### ISSUE THREAD

**Issue by cmillion** [nkarasiak/MuseoToolBox#19]
I think that the [paper](https://github.com/nkarasiak/MuseoToolBox/blob/master/paper.md) would benefit from a more specific comparison to the state-of-the-art in the field and how this package improves or differs. It may simply be that the explanation is unclear; the second sentence in the opening paragraph of the paper is very long and difficult to parse. There are also no references provided.

Tagging: openjournals/joss-reviews#1978

**Comment by nkarasiak** [comment]
Dear Chase,

I'll update the article as asked, but regarding the references, the paper.md file is to generate with JOSS in order to see them : https://github.com/openjournals/joss-papers/blob/joss.01978/joss.01978/10.21105.joss.01978.pdf
[That's what did the awesome whedon](https://github.com/openjournals/joss-reviews/issues/1950#issuecomment-565115635)

Kind regards,
Nicolas.

**Comment by cmillion** [comment]
Oh, I see. That's my mistake re: references. Thank you.

**Comment by nkarasiak** [comment]
Hello Chase,
Here is [the new version of the paper](https://github.com/nkarasiak/MuseoToolBox/files/4180641/mtb_0121b2.pdf).
It is generated from the [develop branch](https://github.com/nkarasiak/MuseoToolBox/tree/develop).
Kind regards,
Nicolas.

**Comment by mollenburger** [comment]
adding here another couple of comments on the software paper:

- the summary is very technical and not understandable by a non-specialist in machine learning and its application to remote sensing/raster data. A sentence or two at the beginning about how Museo is used would be helpful. For example, classification of an RS image by land cover type is a common thing to do--how does Museo make that easier? (e.g. extracting ROIs, transforming rasters/raster bands, fitting various models, performing spatial cross-validation, etc.)

- the figures aren't referred to anywhere in the text, it would be good to refer to Figure 2 in the section on RasterMath

- There's a lot of focus on RasterMath--how is it different from the tools provided in e.g. rasterio or xarray?

**Comment by nkarasiak** [comment]
Hello @mollenburger,

I'm curently working with a native English speaker on the rewriting of the paper. Figures of course are now referred in the text.

For RasterMath, the idea is to be very high-end user, so it could have been built upon rasterio but it is not the case. It differs from rasterio because the aim of RasterMath is only to ease the adaptation of a vector function (i.e. function initially programmed for an array) to a raster. There is absolutely no need to ask for opening a raster in writing mode, to define the number of output bands, the projection, the block size, etc...

**Comment by nkarasiak** [comment]
Hello @mollenburger  and @cmillion,
Here is the new paper version corrected and proofread by a native english colleague.
Here you will find the new paper : [mtb_beta.pdf](https://github.com/nkarasiak/MuseoToolBox/files/4307825/mtb_beta.pdf)

Tell me if it's okay for you.
Kind regards,
Nicolas.
